### ISSUE TITLE
local image is not exported correctly

### ISSUE THREAD

**Issue by Tokubara** [orgtre/anki-editor#14]
```
[[file:/Users/quebec/notes/vx_attachments/Pasted_image_20220915140022.png]]
```

```
<div id="org21164dc" class="figure">
<p><img src="file:%2F%2F%2FUsers%2Fquebec%2Fnotes%2Fvx_attachments%2FPasted_image_20220915140022.png" alt="Pasted_image_20220915140022.png" />
</p>
</div>
```
<img width="626" alt="image" src="https://user-images.githubusercontent.com/32409331/204775091-f5e1ac49-862d-49d4-bbfa-1893f177891f.png">

**Comment by orgtre** [comment]
Hi, did you resolve this issue? If so, may I ask how? I've also seen this happening, but not in a consistent way, so I've not been able to troubleshoot.

**Comment by Tokubara** [comment]
I read [this issue](https://github.com/louietan/anki-editor/issues/35), I put this piece of code in the end of the org file, and then I find that the files in the links are pushed to anki media directory.
```
# local variables:
# eval: (anki-editor-mode +1)
# end:
```
