### ISSUE TITLE
Make this a standalone repo instead of a fork of louietan/anki-editor

### ISSUE THREAD

**Issue by orgtre** [orgtre/anki-editor#19]
This has several advantages, for example code search on Github web would be possible. I'm not sure what the disadvantages would be.

**Comment by renatgalimov** [comment]
@orgtre , let's create an organization called `anki-editor`?

**Comment by shunlog** [comment]
@orgtre sure, go ahead. There's no reason for this to be a fork anymore since the previous repo is unmaintained. It seems you [have to contact the GitHub support](https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project) to do that btw.

**Comment by orgtre** [comment]
This is now a standalone repo (see [here](https://github.com/orgtre/anki-editor/issues/31#issuecomment-2094799248) for context).
