### ISSUE TITLE
Define Anki field in heading property

### ISSUE THREAD

**Issue by renatgalimov** [orgtre/anki-editor#21]
I'm going to extend this package to make it collect card fields from properties.

For example, I want to convert this

```
** Keyhole view                                                        :anki:
:PROPERTIES:
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: Finearts
:ANKI_NOTE_ID: 1679163953504
:END:

**** Front
What is a keyhole view in arts?

**** Back
A keyhole view is a composition technique in art where the artist
creates a visual "window" within the painting that invites the viewer
to look into a deeper, more distant space. It's usually created by
framing the edges of the painting with elements such as archways,
doorways, or other architectural features that create a visual
"keyhole" through which the viewer can see the distant space beyond.
```

Into 

```
** Keyhole view                                                        :anki:
:PROPERTIES:
:ID:       8EB03AE2-447F-4CC9-B1DC-45F4331C30DF
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK: Finearts
:ANKI_NOTE_ID: 1679163953504
:ANKI_FIELD_FRONT: What is a keyhole view in arts?
:END:

A keyhole view is a composition technique in art where the artist
creates a visual "window" within the painting that invites the viewer
to look into a deeper, more distant space. It's usually created by
framing the edges of the painting with elements such as archways,
doorways, or other architectural features that create a visual
"keyhole" through which the viewer can see the distant space beyond.
```

I'm going to implement this myself. If anybody is working on a similar feature or already implemented it, please let me know.

**Comment by orgtre** [comment]
Thanks for this very useful contribution!

One big advantage of storing fields in properties is that it becomes straightforward to view and edit notes from Org Mode's [Column View](https://orgmode.org/manual/Column-View.html) (and even more so with my extension [orgtre/org-colviewx](https://github.com/orgtre/org-colviewx)). For this reason it has already [been suggested at the original repo](https://github.com/louietan/anki-editor/issues/46), but has unfortunately never been implemented. (It is also possible to get headings into column view by including ITEM in the column specification, and to get subheadings and any arbitrary other part of an entry into it by setting a suitable `org-columns-modify-value-for-display-function`, see [here](https://emacs.stackexchange.com/a/75937/33424) for an example.)

A further advantage is that it allows for a much more compact representation of a note containing several short fields. Note, however, that for your example note a (in my opinion) nicer representation would be the following, which is already supported:

```text
** What is a keyhole view in arts?                                         :anki:
:PROPERTIES:
:ID:             8EB03AE2-447F-4CC9-B1DC-45F4331C30DF
:ANKI_NOTE_TYPE: Basic
:ANKI_DECK:      Finearts
:ANKI_NOTE_ID:   1679163953504
:END:

A keyhole view is a composition technique in art where the artist
creates a visual "window" within the painting that invites the viewer
to look into a deeper, more distant space. It's usually created by
framing the edges of the painting with elements such as archways,
doorways, or other architectural features that create a visual
"keyhole" through which the viewer can see the distant space beyond.
```

I'll give some comments on the implementation in your pull request as soon as I get to examine it in more detail. For now, I can say that it'd be nice if the property fields behave like the subheading fields as much as possible. So for example, I don't think the "ANKI_FIELD_" prefix should be needed as field names are retrieved from the "ANKI_NOTE_TYPE", special property names are unlikely to overlap with field names, and we don't use a prefix for subheading fields. (At least we could make it optional with "" as allowed value.)

**Comment by renatgalimov** [comment]
Thanks for your reply. 

> Note, however, that for your example note a (in my opinion) nicer representation would be the following, which is already supported:

The reason why I want to get fields from properties is that in my case Anki field is just an extension of a node and changing the heading is not an option.
