### ISSUE TITLE
anki-editor-api-check: Failed to connect to Anki: End of file while parsing JSON

### ISSUE THREAD

**Issue by doolio** [orgtre/anki-editor#5]
This may not be a bug but it did not occur previously when on the `master` branch from `louietan/anki-editor` and the following config:

```emacs-lisp
(use-package anki-editor
  :after org
  :demand t
  :config (anki-editor-mode))
```
(The use of `:after` and `:demand` here is because I lazy load my packages as much as possible.)

Switching to this fork my `use-package` form becomes:

```emacs-lisp
(use-package anki-editor
  :straight (:fork "orgtre")
  :after org
  :demand t
  :config (anki-editor-mode))
```
So it seems with the merge of the `louietan/anki-editor:develop` branch Anki needs to be running to use the minor mode. This makes sense but it is odd I saw no such message when on the `loueitan/anki-editor:master` branch. Indeed the `develop` branch introduced changes to the API but nothing as yet stands out which would point to why I didn't see this message before.

**Comment by orgtre** [comment]
Yes, I see the same behavior. This is because a function `anki-editor-api-check` has been introduced which is called in `anki-editor-setup-minor-mode` (which in turn is called by `anki-editor-mode`). I'd say this is fine. Or is there something we should change here? Maybe a clearer error message?

**Comment by doolio** [comment]
> Maybe a clearer error message? 

Yes, as a minimum I think.

> Or given that there are some commands in anki-editor which don't really require Anki running, we might want to perform this check only when calling those that require it?

This makes sense.

**Comment by orgtre** [comment]
After some consideration, I think it's best to settle with just the clearer message. Almost all commands anki-editor provides do in fact need Anki running. Adding the check to each command would add an extra API call to each, which is undesirable. I'm also consciously only adding the clearer error message to `anki-editor-api-check`. If Anki or AnkiConnect are closed down subsequently other commands will also fail with "End of file while parsing JSON", but we don't want to modify the error message each time as right now the error messages are generated outside anki-editor and simply passed on.

If you really want to avoid the call to `anki-editor-api-check` I suggest commenting that line. If more people are disturbed by  this I guess we could add a custom option too in the future.
