### ISSUE TITLE
Review pull requests of louietan/anki-editor

### ISSUE THREAD

**Issue by cmirdesouza** [orgtre/anki-editor#6]
I was reading the pull requests of the original repo and i don't know too much about emacs-lisp to review them and see what would be interesting to implement or if it is already implemented.
How can we proceed about that?

**Comment by orgtre** [comment]
I'll try to look into it. Meanwhile, if you're new to Emacs Lisp and want to learn, I think one of the best ways is still to simply work though this [Introduction to Programming in Emacs Lisp](https://www.gnu.org/software/emacs/manual/eintr.html). It doesn't take too long and will get you far enough to start understanding and writing your own Elisp. The rest one can then pick up while actually working on issues and projects I think.

**Comment by cmirdesouza** [comment]
Thanks, i'm trying to get the basics of emacs-lisp quickly so i can help more and not only report things kkkkkkk.

**Comment by orgtre** [comment]
OK, I went through all the pull requests and added the ones with new functionality. I opened a [separate](https://github.com/orgtre/anki-editor/issues/10) issue for the only two (#81 and #102) I couldn't address directly and am closing this issue.
