### ISSUE TITLE
Unexpected behavior on omission of not-first fields

### ISSUE THREAD

**Issue by cmirdesouza** [orgtre/anki-editor#8]
The idea that I get of omitting fields is for it to only work when we omit the first field.
If I don't omit the first field and I omit other fields it duplicates the first field and answer on the third omitted field.
These issue was first described [here](https://github.com/louietan/anki-editor/issues/89#issuecomment-803664372)

```org
* Example Normal Card
:PROPERTIES:
:ANKI_NOTE_TYPE: Omissão de Palavras
:END:
** Pergunta Orientadora
** Texto
** Verso Extra
* header1
:PROPERTIES:
:ANKI_NOTE_TYPE: Omissão de Palavras
:ANKI_NOTE_ID: 1667141134070
:END:
** Pergunta Orientadora
Question1?
** Texto
{{c1::Cloze1}}
```
The result is that the third field Verso Extra, has the following html:
```html
<div id="outline-container-orgcc98548" class="outline-2">
<h2 id="orgcc98548"><span class="section-number-2">1.</span> Pergunta Orientadora</h2>
<div class="outline-text-2" id="text-1">
<p>
Question1?
</p>
</div>
</div>
```

**Comment by orgtre** [comment]
The logic is currently as follows: When one field subheading is omitted, if there is content before the first subheading this content is mapped to the missing field, if there is no content before the first subheading the heading is mapped to the missing field. Moreover, extra subheadings which don't match any note-type fields are counted as part of the content before the first subheading. I know it's a bit convoluted, but like this it is consistent across all cases while maximally flexible, I think.

**Comment by cmirdesouza** [comment]
I found alternated solutions to my use case testing many layouts, I agree with you that the flexibility is the best design decision.
